name: End-to-End-tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        user: actions/checkout@v3
      - name: Cypress run
        user: cypress-io/github-action@v5